# Generated by Django 5.2.9 on 2025-12-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('AttendanceLogId', models.AutoField(primary_key=True, serialize=False)),
                ('AttendanceDate', models.DateTimeField()),
                ('InTime', models.CharField(blank=True, max_length=510, null=True)),
                ('OutTime', models.CharField(blank=True, max_length=510, null=True)),
                ('Status', models.CharField(max_length=510)),
            ],
            options={
                'db_table': 'AttendanceLogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentFName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceLogs122025',
            fields=[
                ('DeviceLogId', models.AutoField(db_column='DeviceLogId', primary_key=True, serialize=False)),
                ('DownloadDate', models.DateTimeField(db_column='DownloadDate', null=True)),
                ('DeviceId', models.IntegerField(db_column='DeviceId', null=True)),
                ('UserId', models.CharField(db_column='UserId', max_length=100)),
                ('LogDate', models.DateTimeField(db_column='LogDate')),
                ('Direction', models.CharField(db_column='Direction', max_length=200, null=True)),
                ('AttDirection', models.CharField(db_column='AttDirection', max_length=510, null=True)),
            ],
            options={
                'db_table': 'DeviceLogs_12_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.IntegerField()),
                ('EmployeeCode', models.CharField(db_column='EmployeeCode', max_length=50, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PasswordHash', models.CharField(max_length=255)),
                ('Employee', models.OneToOneField(db_column='EmployeeCode', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.employees')),
            ],
            options={
                'db_table': 'EmployeePasswords',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('AttendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('AttendanceDate', models.DateField()),
                ('PunchIn', models.DateTimeField(blank=True, null=True)),
                ('PunchOut', models.DateTimeField(blank=True, null=True)),
                ('WorkingSeconds', models.IntegerField(default=0)),
                ('BreakSeconds', models.IntegerField(default=0)),
                ('Status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('WEEKLY_OFF', 'Weekly Off'), ('HALF_DAY', 'Half Day')], default='ABSENT', max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Employee', models.ForeignKey(db_column='EmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendances', to='myapp.employees')),
            ],
            options={
                'db_table': 'EmployeeAttendance',
                'managed': True,
                'unique_together': {('Employee', 'AttendanceDate')},
            },
        ),
    ]
