# Generated by Django 5.2.9 on 2025-12-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(max_length=20)),
                ('ReportsToEmpCode', models.CharField(blank=True, max_length=20, null=True)),
                ('Role', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
