# Generated by Django 5.2.9 on 2026-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employeereporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField()),
                ('ProjectName', models.CharField(max_length=200)),
                ('MLV_ID', models.CharField(max_length=50)),
                ('MLV_Name', models.CharField(max_length=200)),
                ('Team', models.CharField(max_length=100)),
                ('FPC_TotalCount', models.IntegerField(default=0)),
                ('FPC_TotalPage', models.IntegerField(default=0)),
                ('FPC_TotalIcd', models.IntegerField(default=0)),
                ('FPC_Target', models.IntegerField(default=0)),
                ('FPC_AchievedPercent', models.FloatField(default=0.0)),
                ('Audit_TotalCount', models.IntegerField(default=0)),
                ('Audit_TotalPage', models.IntegerField(default=0)),
                ('Audit_TotalIcd', models.IntegerField(default=0)),
                ('Audit_ErrorCount', models.IntegerField(default=0)),
                ('Audit_Target', models.IntegerField(default=0)),
                ('Audit_EFPercent', models.FloatField(default=0.0)),
                ('Audit_AchievedPercent', models.FloatField(default=0.0)),
                ('Quality_TotalChart', models.IntegerField(default=0)),
                ('Quality_TotalIcd', models.IntegerField(default=0)),
                ('Quality_TotalErrors', models.IntegerField(default=0)),
                ('Quality_QAPercent', models.FloatField(default=0.0)),
                ('Assessment_TotalQues', models.IntegerField(default=0)),
                ('Assessment_TotalCorrect', models.IntegerField(default=0)),
                ('Assessment_Percent', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'MasterData',
                'managed': True,
                'unique_together': {('MLV_ID', 'Date', 'ProjectName')},
            },
        ),
    ]
