# Generated by Django 5.2.9 on 2026-03-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_masterdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdata',
            old_name='Audit_EFPercent',
            new_name='Audit_U1Percent',
        ),
    ]
