# Generated by Django 5.2.9 on 2026-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_audit_efpercent_masterdata_audit_u1percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CompanyAnnouncements',
                'managed': True,
            },
        ),
    ]
