# Generated by Django 5.2.9 on 2026-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_companyannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNo', models.CharField(max_length=20)),
                ('FatherName', models.CharField(max_length=200)),
                ('MotherName', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('PlaceOfBirth', models.CharField(max_length=200)),
                ('BloodGroup', models.CharField(max_length=10)),
                ('AadhaarNumber', models.CharField(max_length=20)),
                ('ResidentialAddress', models.TextField()),
                ('PermanentAddress', models.TextField()),
                ('BankName', models.CharField(max_length=200)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('IFSCCode', models.CharField(max_length=20)),
                ('Photo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OnboardingRequests',
                'managed': True,
            },
        ),
    ]
