# Generated by Django 5.2.9 on 2026-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_onboardingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='EmployeeCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
