# Generated by Django 5.2.9 on 2026-03-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_onboardingrequest_employeecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='DateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
