# Generated by Django 5.2.9 on 2026-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_onboardingrequest_dateofjoining'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('ConfigKey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ConfigValue', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AppConfigurations',
                'managed': True,
            },
        ),
    ]
