# Generated by Django 5.2.9 on 2026-03-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='AAPCCertification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='BGVDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='CredentialNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='Designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='EmergencyContactNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='MaritalStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='PANNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='PreviousOrganization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='Qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='TotalExperience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='UANNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
