# Generated by Django 5.2.9 on 2026-03-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_onboardingrequest_aapccertification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.CharField(max_length=50)),
                ('SelfRating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('SelfComments', models.TextField(blank=True, null=True)),
                ('ManagerRating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ManagerComments', models.TextField(blank=True, null=True)),
                ('FinalRating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('Status', models.CharField(choices=[('PENDING', 'Pending'), ('SELF_SUBMITTED', 'Self Submitted'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('SubmittedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='myapp.employees')),
            ],
            options={
                'db_table': 'Appraisals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.CharField(max_length=50)),
                ('FeedbackText', models.TextField()),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Relationship', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('FromEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='myapp.employees')),
                ('ToEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='myapp.employees')),
            ],
            options={
                'db_table': 'Feedback360',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoalKRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.CharField(max_length=50)),
                ('KRA_Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Weightage', models.IntegerField(default=25)),
                ('Status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('ManagerComments', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='myapp.employees')),
            ],
            options={
                'db_table': 'GoalKRAs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Issues', models.TextField()),
                ('Objectives', models.TextField()),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='myapp.employees')),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_pips', to='myapp.employees')),
            ],
            options={
                'db_table': 'PerformanceImprovementPlans',
                'managed': True,
            },
        ),
    ]
