# Generated by Django 5.2.9 on 2026-03-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appraisal_feedback360_goalkra_pip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback360',
            name='FromEmployee',
        ),
        migrations.RemoveField(
            model_name='feedback360',
            name='ToEmployee',
        ),
        migrations.RemoveField(
            model_name='goalkra',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='pip',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='pip',
            name='Manager',
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseType', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Internet', 'Internet'), ('Other', 'Other')], max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField()),
                ('ExpenseDate', models.DateField()),
                ('Receipt', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Status', models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager'), ('PENDING_FINANCE', 'Pending Finance'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED_FOR_PAYMENT', 'Approved for Payment'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING_MANAGER', max_length=30)),
                ('ManagerRemarks', models.TextField(blank=True, null=True)),
                ('FinanceRemarks', models.TextField(blank=True, null=True)),
                ('AdminRemarks', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Employee', models.ForeignKey(db_column='EmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_claims', to='myapp.employees')),
            ],
            options={
                'db_table': 'ExpenseClaims',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Appraisal',
        ),
        migrations.DeleteModel(
            name='Feedback360',
        ),
        migrations.DeleteModel(
            name='GoalKRA',
        ),
        migrations.DeleteModel(
            name='PIP',
        ),
    ]
