# Generated by Django 5.2.9 on 2026-03-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_feedback360_fromemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetTag', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('AssetType', models.CharField(choices=[('Laptop', 'Laptop'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Phone', 'Phone'), ('Other', 'Other')], max_length=50)),
                ('SerialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Model', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('RETIRED', 'Retired'), ('UNDER_REPAIR', 'Under Repair')], default='AVAILABLE', max_length=30)),
                ('PurchaseDate', models.DateField(blank=True, null=True)),
                ('WarrantyExpiry', models.DateField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Assets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllocatedDate', models.DateField()),
                ('ReturnedDate', models.DateField(blank=True, null=True)),
                ('ConditionOnAllocation', models.CharField(blank=True, max_length=100, null=True)),
                ('ConditionOnReturn', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='myapp.asset')),
                ('Employee', models.ForeignKey(db_column='EmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_allocations', to='myapp.employees')),
            ],
            options={
                'db_table': 'AssetAllocations',
                'managed': True,
            },
        ),
    ]
