# Generated by Django 5.2.9 on 2026-03-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_asset_assetallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PulseSurveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HelpdeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('HR', 'HR Support'), ('IT', 'IT Support'), ('Admin', 'Admin Support'), ('Payroll', 'Payroll Support')], max_length=50)),
                ('Subject', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('Status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('Resolution', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('AssignedTo', models.ForeignKey(blank=True, db_column='AssignedTo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tickets', to='myapp.employees')),
                ('Employee', models.ForeignKey(db_column='EmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='helpdesk_tickets', to='myapp.employees')),
            ],
            options={
                'db_table': 'HelpdeskTickets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('FromEmployee', models.ForeignKey(db_column='FromEmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kudos_sent', to='myapp.employees')),
                ('ToEmployee', models.ForeignKey(db_column='ToEmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kudos_received', to='myapp.employees')),
            ],
            options={
                'db_table': 'KudosWall',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.ForeignKey(db_column='EmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.employees')),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.pulsesurvey')),
            ],
            options={
                'db_table': 'SurveyResponses',
                'managed': True,
                'unique_together': {('Survey', 'Employee')},
            },
        ),
    ]
