# Generated by Django 5.2.9 on 2026-03-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_pulsesurvey_helpdeskticket_kudos_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='Rating',
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=500)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.pulsesurvey')),
            ],
            options={
                'db_table': 'SurveyQuestions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.surveyresponse')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.surveyquestion')),
            ],
            options={
                'db_table': 'SurveyAnswers',
                'managed': True,
            },
        ),
    ]
