# Generated by Django 5.2.9 on 2026-03-20 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_surveyresponse_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='Category',
            field=models.CharField(choices=[('Teamwork', 'Teamwork'), ('Innovation', 'Innovation'), ('Support', 'Support'), ('Leadership', 'Leadership'), ('Great Work', 'Great Work'), ('Other', 'Other')], default='Great Work', max_length=50),
        ),
        migrations.CreateModel(
            name='KudosLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.ForeignKey(db_column='EmployeeCode', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.employees')),
                ('Kudos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='myapp.kudos')),
            ],
            options={
                'db_table': 'KudosLikes',
                'managed': True,
                'unique_together': {('Kudos', 'Employee')},
            },
        ),
    ]
