# Generated by Django 5.2.9 on 2026-03-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_kudos_category_kudoslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskticket',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='IsSLAExceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='ResolvedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
